name: "i386/debian9"

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  CORES: 2
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  LC_LANG: C.UTF-8

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: "i386/debian:9"
    timeout-minutes: 120
    strategy:
      matrix:
        env:
          - BUILD_MODE: normal
            GPG_VERSION: stable
            CPU: i386
            SUDO: ""
    env: ${{ matrix.env }}
    continue-on-error: true
    steps:
      - name: Installing prerequisites
        run: |
          ${SUDO} apt update
          ${SUDO} apt -y install git python3 g++ wget autoconf libtool curl libncurses5-dev rubygems make libssl-dev zlib1g-dev libbz2-dev ruby-dev
          ${SUDO} ln -s /usr/bin/python3 /usr/bin/python
          cd $GITHUB_WORKSPACE
          git init
          git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          git fetch origin $GITHUB_SHA
          git reset --hard FETCH_HEAD
      - name: Setup environment
        run: |
          . ci/gha/setup-env.inc.sh
        shell: bash
      - name: Building dependencies
        run: |
          set -euxo pipefail
          ci/before_install.sh
          . ci/env.inc.sh
          ./ci/install.sh
        shell: bash
      - name: Building and Testing
        run: |
          set -x
          ./ci/run.sh
        shell: bash
